### ISSUE TITLE
jipdate: a --dry-run option would be useful

### ISSUE THREAD

**Issue by pm215** [Linaro/jipdate#16]
There doesn't seem to be any way to tell jipdate "do this, but instead of actually changing anything on the JIRA server just tell the user what would have been done". This is a really useful thing to have when you're trying out a new tool, because it means you can test whether you have the command line syntax right and so on without worrying about whether you're going to mess up the server at all. The usual syntax for this is "--dry-run". (You could use -n for the short option, by analogy with git.)

**Comment by jbech-linaro** [comment]
You could use the `-p` parameter for this, which was introduced by @vingu-linaro. I think the end result would be the same as using a `--dry-run` parameter. Changing the current `-p` to `-n` would probably be confusing for people using the `-p` parameter, @vingu-linaro ? Alternatively we could add it, but call the same functions as the `-p`.

Also, although not clearly stated, there won't be any updates to the Jira server as long as one doesn't answer `y` to the 
```
Are you sure you want to update Jira with the information above? [y/n]
```
Which is only shown when you have made actual changes. That in combination with the `-t` (test server) should make it pretty safe to experiment with command line parameters. Having that said, I should clarify this in the readme file.

**Comment by vingu-linaro** [comment]
I don't mind of using -n instead of -p. May be we can keep both during a transition period with a warning for -p

**Comment by chazy** [comment]
But that's not what pm215 was asking for, because it only applied when using -q.  I'll add a --dry-run option.

**Comment by pm215** [comment]
Christoffer's now-merged commits provide the --dry-run option, and I've tested and it works OK for me, so I'm going to close this issue. Thanks!
