### ISSUE TITLE
jipdate writes config.yml to current working directory

### ISSUE THREAD

**Issue by pm215** [Linaro/jipdate#18]
jipdate writes the config.yml to your current working directory (wherever that happens to be) rather than looking in a well defined place for it (eg user's home directory, same directory as the jipdate script). This is unexpected (to me, anyway) and means that effectively you have to run jipdate from a well defined directory if you don't want it to forget your user settings and drop config.yml files everywhere.

**Comment by jbech-linaro** [comment]
Hi Peter, apologize for the delayed answer (been on vacation). I think you are right, I will update the script so it checks for the `config.yml` in the users home directory. What is best here? `$HOME/.jipdate` or `$HOME/.config/jipdate`. I can of course look in both of them and as a final thing just try the current path.

**Comment by pm215** [comment]
If you really want to be fancy you can follow the XDG Base Directory Specification (https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html) which says "file in the directory specified in $XDG_CONFIG_HOME; if that variable isn't set then use $HOME/.config". But I don't think it matters very much :-)

**Comment by jbech-linaro** [comment]
I haven't forgot about this, I've just been too busy with other stuff. I will fix it sooner or later.

**Comment by jbech-linaro** [comment]
One of the commit in #19 will fix this issue (I hope).
