### ISSUE TITLE
jipdate configured to use linaro.atlassian.net still says it will be updating projects.linaro.org

### ISSUE THREAD

**Issue by pm215** [Linaro/jipdate#44]
I configured jipdate with the new url/token stuff to access linaro.atlassian.net, and it does correctly seem to read from there, but it still prints a message saying it is going to update projects.linaro.org:

```
$ EDITOR=/bin/true JIRA_USERNAME=peter.maydell@linaro.org ~/linaro/jipdate/jipdate.py -v -f ~/jipdate.txt
[DEBUG] initiate_config():104   Using config file: /home/petmay01/.config/jipdate/.jipdate.yml
[DEBUG] get_jira_instance():114   Accessing https://linaro.atlassian.net with peter.maydell@linaro.org using token based authentication
[DEBUG] _new_conn():975   Starting new HTTPS connection (1): linaro.atlassian.net:443
[DEBUG] _make_request():461   https://linaro.atlassian.net:443 "GET /rest/api/2/serverInfo HTTP/1.1" 200 None
[DEBUG] _make_request():461   https://linaro.atlassian.net:443 "GET /rest/api/2/field HTTP/1.1" 200 None
[DEBUG] _make_request():461   https://linaro.atlassian.net:443 "GET /rest/api/2/resolution HTTP/1.1" 200 None
[DEBUG] _make_request():461   https://linaro.atlassian.net:443 "GET /rest/api/2/issue/UM-2 HTTP/1.1" 200 None
[DEBUG] _make_request():461   https://linaro.atlassian.net:443 "GET /rest/api/2/issue/QEMU-406 HTTP/1.1" 200 None
These JIRA cards will be updated as follows:
[snip]

Server to update: https://projects.linaro.org

Are you sure you want to update Jira with the information above? [y/n]
```

(I haven't tried typing 'y' to see if it really will update projects.linaro.org or if it will actually update the atlassian server...)

**Comment by jbech-linaro** [comment]
Hi Peter,

Based on the debug log it looks like it indeed uses the atlassian, so it's probably just the print that is incorrect. I'll have a look at it, thanks for reporting the issue.

// Joakim

**Comment by jbech-linaro** [comment]
We took the server details from different locations, hence the correct connection, but the wrong confirmation url. I've wrapped them all in a single function now instead. The patch (https://github.com/Linaro/jipdate/commit/459f9e66ac837911238a2a89a1a419f0f35ed634) fixing this has been merged, so please update to latest and hopefully it should work. Based on this I'm closing this issue.

**Comment by pm215** [comment]
That commit doesn't seem to be in master, only on your branch ?

**Comment by jbech-linaro** [comment]
Oh, bummer, I pushed the branch as a new branch and not to master, thanks for catching that. I've fixed it now.
